### ISSUE TITLE
Please publish the plugin

### ISSUE THREAD

**Issue by pcav** [tudelft3d/prepair-qgis#1]
Would you mind publishing it under http://plugins.qgis.org for easier distribution?
Thanks.

**Comment by hugoledoux** [comment]
I'd like too, but it calls an executable (prepair), which is different for different platforms. I could state that it must be in your path, but I've read that it's not really allowed.

**Comment by pcav** [comment]
Best if you can make your plugin a subplugin of Processing (see our lwgeom for an example). In this case, the user is expected to add the path manually.

**Comment by hugoledoux** [comment]
Interesting. I'll have a look and get back to you if I need help.

**Comment by hugoledoux** [comment]
@pcav It's been published, there was a problem with the first version but now it is solved (I think). It should be approved in the next few hours. Your feedback is appreciated.
