### ISSUE TITLE
Mac OS X - probable Python 2.6 incompatibilities

### ISSUE THREAD

**Issue by cbertelli** [tudelft3d/prepair-qgis#10]
After installing I get this message:
The plugin is corrupt. Python Message:
zero length field name in format
This seems to be due to incompatibilities with Python 2.6

**Comment by bmmeijers** [comment]
String formatting indeed did change between 2.6 and 2.7

This is for example allowed in 2.7:

localePath = os.path.join(self.plugin_dir, 'i18n', 'prepair_{}.qm'.format(locale))

But in 2.6 you should write:

localePath = os.path.join(self.plugin_dir, 'i18n', 'prepair_{0}.qm'.format(locale))

Note that {} is changed to {0}

Btw. I think this is the only location that needs the change ;-) (Just grepped the source tree, and this is the only case that uses .format() this way)

**Comment by cbertelli** [comment]
I knew, so the plugin is supposed to work only on 2.7 or it's useful to
spot these issues and fix them? Are there forward incompatibilities that
prevent a 2.6-compatibile plugin from working in 2.7?
Thanks for the prompt answer.
c

On Tue, Oct 7, 2014 at 3:49 PM, bmmeijers notifications@github.com wrote:

> String formatting indeed did change between 2.6 and 2.7
> 
> This is for example allowed in 2.7:
> 
> localePath = os.path.join(self.plugin_dir, 'i18n',
> 'prepair_{}.qm'.format(locale))
> 
> But in 2.6 you should write:
> 
> localePath = os.path.join(self.plugin_dir, 'i18n',
> 'prepair_{0}.qm'.format(locale))
> 
> Note that {} is changed to {0}
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tudelft-gist/prepair-qgis/issues/10#issuecomment-58186568
> .

## 

---

Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel. +39(0)10 2475439  fax +39(0)10 2475439  gsm:+39 393 1590711

##    e-mail: bertelli@charta.acme.com      http://www.charta.acme.com

**Comment by bmmeijers** [comment]
I guess if that line is fixed everything should work, also on Py2.6. So, would be useful if you can check if it works after making that small change in prepair.py.

**Comment by cbertelli** [comment]
I did, but unfortunately it didn't fix the issue. This is the message:

Traceback (most recent call last):
  File
"/Applications/QGIS_2.5-dev_SnoLeo_7.app/Contents/MacOS/../Resources/python/qgis/utils.py",
line 208, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/carlo/.qgis2/python/plugins/prepair/**init**.py", line 27,
in classFactory
    return Prepair(iface)
  File "/Users/carlo/.qgis2/python/plugins/prepair/prepair.py", line 46, in
**init**
    localePath = os.path.join(self.plugin_dir, 'i18n',
'prepair_{0}.qm'.format(locale))
ValueError: zero length field name in format

On Tue, Oct 7, 2014 at 3:58 PM, bmmeijers notifications@github.com wrote:

> I guess if that line is fixed everything should work. So, would be useful
> if you can check if it works after making that small change in prepair.py.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tudelft-gist/prepair-qgis/issues/10#issuecomment-58188023
> .

## 

---

Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel. +39(0)10 2475439  fax +39(0)10 2475439  gsm:+39 393 1590711

##    e-mail: bertelli@charta.acme.com      http://www.charta.acme.com

**Comment by bmmeijers** [comment]
Is there still some cached version around of the Python module (.pyc / .pyo) ?

**Comment by cbertelli** [comment]
Yes (stupid me!), after deleting and restarting QGIS, it works.
Thanks.
c

On Tue, Oct 7, 2014 at 4:45 PM, bmmeijers notifications@github.com wrote:

> Is there still some cached version around of the Python module (.pyc /
> .pyo) ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tudelft-gist/prepair-qgis/issues/10#issuecomment-58195807
> .

## 

---

Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel. +39(0)10 2475439  fax +39(0)10 2475439  gsm:+39 393 1590711

##    e-mail: bertelli@charta.acme.com      http://www.charta.acme.com

**Comment by hugoledoux** [comment]
fixed it and pushed it to master, thanks for pointing out.
