### ISSUE TITLE
2 more issues

### ISSUE THREAD

**Issue by AlainFELER** [tudelft3d/prepair-qgis#12]
I tried prepair in command-line upon 7 faulty polygons.

It doesn't work for one of them, and half-works for the other.

The first is not treated because prepair considers the first feature is not a polygon, which it is according to QGIS.
Here is the json source of it : 
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },

"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 157797.20798569021, 6790222.8119961172 ], [ 157806.6711442963, 6790223.3586888742 ], [ 157816.80069214758, 6790224.1686867084 ], [ 157825.76998946804, 6790225.9694257025 ], [ 157834.1397521277, 6790227.850495059 ], [ 157840.87049916713, 6790229.8208203753 ], [ 157850.60970250925, 6790234.5112210754 ], [ 157858.77027501725, 6790238.4094751282 ], [ 157869.90911143459, 6790243.5997092007 ], [ 157877.01941998617, 6790246.679039822 ], [ 157886.35965242074, 6790251.4296882935 ], [ 157895.52951349481, 6790258.5790906874 ], [ 157904.96032310824, 6790263.4591603018 ], [ 157909.70052880922, 6790265.6994848978 ], [ 157917.97971428966, 6790269.5888133543 ], [ 157923.12967389578, 6790271.4297175296 ], [ 157927.77930241788, 6790272.6391357882 ], [ 157935.23898008815, 6790274.3907840028 ], [ 157947.33965988259, 6790277.0796197979 ], [ 157958.35988332785, 6790279.1191184837 ], [ 157959.72069761227, 6790295.1093237177 ], [ 157960.11104212154, 6790301.399637498 ], [ 157957.40019655018, 6790324.0505687483 ], [ 157955.36005342333, 6790339.7908572946 ], [ 157954.02943153179, 6790347.9600090338 ], [ 157954.13941810618, 6790356.0198222212 ], [ 157954.35076485714, 6790371.4097811244 ], [ 157953.93022795487, 6790377.2805918921 ], [ 157951.6895210743, 6790389.0400646226 ], [ 157950.54005354084, 6790394.6096365284 ], [ 157949.2396240423, 6790399.4294583658 ], [ 157947.11106033577, 6790404.119859064 ], [ 157954.87913173484, 6790405.1507654032 ], [ 157957.60938670184, 6790405.6104335971 ], [ 157962.2396058283, 6790405.7510117339 ], [ 157969.33913138229, 6790405.6706813714 ], [ 157977.95043318567, 6790405.1485340055 ], [ 157992.77058494976, 6790412.5991752651 ], [ 157992.82881313632, 6790443.2809115164 ], [ 157993.8704506947, 6790466.98952589 ], [ 157993.99984666484, 6790500.8398487205 ], [ 157993.36580641195, 6790540.0209837621 ], [ 157993.22131424549, 6790549.0402985197 ], [ 157993.38952900632, 6790554.7593741566 ], [ 157992.80077734275, 6790556.0000319993 ], [ 157994.29961399524, 6790564.4704226041 ], [ 157993.38952900632, 6790571.0396612622 ], [ 157998.48557362484, 6790572.1620549578 ], [ 157999.16705906682, 6790580.672610743 ], [ 157999.96068768285, 6790583.8501229193 ], [ 158001.55010151432, 6790588.7279611332 ], [ 158008.58492908324, 6790603.4775085226 ], [ 158014.93827121018, 6790615.5047491333 ], [ 158035.94139374106, 6790649.1297006672 ], [ 158055.04886531085, 6790640.3089804174 ], [ 158092.76994716527, 6790622.9308450054 ], [ 158100.54880156193, 6790619.8894481696 ], [ 158102.91027801437, 6790610.4907955788 ], [ 158093.80080172641, 6790607.6390676582 ], [ 158053.06048057193, 6790597.0109142233 ], [ 158026.90955503471, 6790590.8410959858 ], [ 158009.54030266171, 6790586.0792905204 ], [ 158016.37025327806, 6790576.1093997872 ], [ 158021.85017260758, 6790567.4091750858 ], [ 158034.81996200094, 6790545.5793986702 ], [ 158051.85062825237, 6790517.6690599779 ], [ 158066.2308337182, 6790493.7797022844 ], [ 158069.69001931639, 6790487.0698854923 ], [ 158084.98893616931, 6790455.6696387632 ], [ 158089.26978617685, 6790446.2107384019 ], [ 158126.93910964322, 6790461.0406161565 ], [ 158140.0210422104, 6790466.5610972829 ], [ 158156.52981138276, 6790473.0009147953 ], [ 158164.20083580434, 6790475.9798324611 ], [ 158169.54920256429, 6790477.9903229596 ], [ 158201.87015927071, 6790490.8208672106 ], [ 158213.64950573968, 6790495.4889539173 ], [ 158220.16027963033, 6790497.7806006912 ], [ 158231.70024355501, 6790502.4799269866 ], [ 158247.40028791502, 6790509.3191649215 ], [ 158237.5705073938, 6790530.8700164612 ], [ 158231.82963952492, 6790543.6090733539 ], [ 158229.83909818646, 6790549.2098848429 ], [ 158256.33076644444, 6790558.9298588894 ], [ 158278.70979945583, 6790567.3087621322 ], [ 158319.92241590074, 6790581.6923600864 ], [ 158327.75087208604, 6790560.0232443977 ], [ 158334.10421421274, 6790530.5219182177 ], [ 158341.59408427635, 6790493.534248393 ], [ 158331.00733733096, 6790489.9059936199 ], [ 158333.76347149198, 6790481.6208091332 ], [ 158338.18881366588, 6790468.1186137851 ], [ 158340.11897021846, 6790461.9911921294 ], [ 158344.43001261889, 6790448.7165994812 ], [ 158345.45008418232, 6790444.6331393085 ], [ 158346.92519824032, 6790439.072493 ], [ 158353.39284014073, 6790409.4595968714 ], [ 158354.18646875699, 6790403.3321752204 ], [ 158355.05989155429, 6790396.3791359328 ], [ 158357.0288668978, 6790380.9601688441 ], [ 158358.85981987347, 6790367.8908649022 ], [ 158360.55922027933, 6790348.620503136 ], [ 158360.75978403282, 6790345.6705936594 ], [ 158350.89981111907, 6790346.9491852857 ], [ 158349.75034358527, 6790349.7495910302 ], [ 158342.90960997134, 6790350.6309936363 ], [ 158331.2898518655, 6790351.4409914743 ], [ 158319.12878728483, 6790352.2799974969 ], [ 158313.5992661668, 6790351.6998337563 ], [ 158309.18902018922, 6790351.0594222434 ], [ 158308.96042064251, 6790351.0995874275 ], [ 158304.34098451328, 6790351.8694200804 ], [ 158298.6799108258, 6790353.0007393742 ], [ 158297.9790159883, 6790357.1109763319 ], [ 158291.34962912533, 6790358.219981635 ], [ 158253.25114235841, 6790367.5695434473 ], [ 158245.95967944898, 6790368.0202860432 ], [ 158227.3805747563, 6790368.4107808685 ], [ 158210.86964898417, 6790369.4796209875 ], [ 158204.11086615152, 6790369.7406946719 ], [ 158172.4498288919, 6790373.0208512023 ], [ 158172.05948438228, 6790368.8704490624 ], [ 158164.97074182564, 6790348.0090998104 ], [ 158161.80916695879, 6790335.5110340118 ], [ 158161.06082693243, 6790328.8190684114 ], [ 158162.1693190753, 6790320.5896688998 ], [ 158162.96941748972, 6790316.6802578513 ], [ 158164.44021834887, 6790310.1311017843 ], [ 158168.50972160534, 6790295.2008110769 ], [ 158170.59946652094, 6790288.8390925294 ], [ 158178.00954240304, 6790273.8708680384 ], [ 158183.54984651832, 6790265.3000644762 ], [ 158189.10956002935, 6790255.1204222394 ], [ 158192.48032504774, 6790247.6006076075 ], [ 158191.00089779089, 6790246.679039821 ], [ 158193.25885746733, 6790239.2194729652 ], [ 158193.25238766894, 6790239.2417869549 ], [ 158170.1530504243, 6790227.2390917335 ], [ 158168.56363659282, 6790226.33314374 ], [ 158180.25024928327, 6790200.9175091302 ], [ 158180.81743495166, 6790195.2430614717 ], [ 158189.89456224721, 6790175.9548485167 ], [ 158164.36689396575, 6790163.4746339079 ], [ 158175.71276393544, 6790147.5893044295 ], [ 158172.64823604561, 6790144.6393949492 ], [ 158175.37202121434, 6790138.286601996 ], [ 158178.0958063826, 6790132.7259556884 ], [ 158181.15817767254, 6790126.1455600373 ], [ 158181.83966311475, 6790124.784406648 ], [ 158184.22270556225, 6790120.3595424313 ], [ 158190.69034746266, 6790107.8793278234 ], [ 158194.88709008985, 6790099.0295993909 ], [ 158203.51133149024, 6790080.9887384744 ], [ 158209.97897339077, 6790068.1671198197 ], [ 158211.96951472899, 6790064.8601865014 ], [ 158221.05958162167, 6790046.6608962575 ], [ 158229.97065075568, 6790029.3206946291 ], [ 158238.42020759673, 6790011.1704951636 ], [ 158246.94955861906, 6789993.7209549844 ], [ 158254.20004613814, 6789977.8802534835 ], [ 158258.42913775763, 6789966.1408633431 ], [ 158258.92946884187, 6789965.5807821956 ], [ 158256.30057405122, 6789964.3200417589 ], [ 158253.02038621192, 6789962.9499627762 ], [ 158248.98970174638, 6789961.5709581915 ], [ 158238.33394361672, 6789958.2974958587 ], [ 158238.67037313897, 6789956.989896046 ], [ 158240.16058339307, 6789952.2905697506 ], [ 158241.2992679294, 6789951.5698278733 ], [ 158242.4206996694, 6789949.7891714713 ], [ 158251.18080683833, 6789934.3010310121 ], [ 158258.8906500506, 6789920.4998281961 ], [ 158259.91934801219, 6789918.6410728311 ], [ 158271.32128956879, 6789898.3799699116 ], [ 158274.28014408273, 6789893.1205624687 ], [ 158258.18112881551, 6789882.9900110094 ], [ 158256.4407530186, 6789881.6779483957 ], [ 158261.87538375857, 6789873.3816069113 ], [ 158256.91951810778, 6789871.4090501973 ], [ 158253.35034593556, 6789870.0501282085 ], [ 158245.78930808837, 6789867.2207142757 ], [ 158235.89914278139, 6789863.4295673743 ], [ 158241.70039543638, 6789847.0198591296 ], [ 158246.78997025604, 6789832.5202284241 ], [ 158248.29096350819, 6789828.07081882 ], [ 158250.91123190068, 6789820.1694349609 ], [ 158257.40906619409, 6789800.3791572293 ], [ 158260.66121824028, 6789796.1394991297 ], [ 158261.26722269983, 6789795.2737163194 ], [ 158250.80987172411, 6789787.0398540059 ], [ 158259.52037710475, 6789772.319314803 ], [ 158262.49001461628, 6789767.260733271 ], [ 158270.05105246336, 6789754.7091138968 ], [ 158254.48040407337, 6789742.5703033367 ], [ 158261.5713032292, 6789733.7406574944 ], [ 158271.43990254134, 6789721.639780716 ], [ 158264.64877071569, 6789718.5002023233 ], [ 158269.16037686972, 6789703.9403238483 ], [ 158276.22971003084, 6789681.1309632706 ], [ 158278.50923570199, 6789674.0797424288 ], [ 158280.70034079405, 6789665.830260328 ], [ 158280.82973676431, 6789665.3795177294 ], [ 158281.87568752165, 6789661.2558923773 ], [ 158240.52289210923, 6789660.1201102864 ], [ 158233.20986320451, 6789650.8397218436 ], [ 158228.70041365025, 6789644.0094095068 ], [ 158224.4195636427, 6789637.9690124122 ], [ 158212.61002478085, 6789620.8207110986 ], [ 158202.0405306312, 6789624.4489658736 ], [ 158200.44033380225, 6789624.9599562446 ], [ 158187.97950189107, 6789629.4294484397 ], [ 158168.22936367034, 6789636.2887689676 ], [ 158167.81960976508, 6789636.9805026567 ], [ 158166.05982457323, 6789639.2096702578 ], [ 158164.70763668674, 6789640.8720625136 ], [ 158162.66533696023, 6789643.5943692913 ], [ 158155.40837964287, 6789636.6837265901 ], [ 158149.38931043807, 6789641.5526392059 ], [ 158142.85050075408, 6789634.0908409525 ], [ 158140.62489006994, 6789631.5738228783 ], [ 158088.98080184381, 6789692.7476264639 ], [ 158065.27546013962, 6789713.4349265937 ], [ 158054.71674898767, 6789717.8664850071 ], [ 158043.08620788413, 6789716.5388026023 ], [ 158033.58207388769, 6789710.6010498647 ], [ 158023.52800701861, 6789688.4454891933 ], [ 158024.04990409769, 6789678.7857629219 ], [ 158032.27948778972, 6789655.2980570477 ], [ 157996.47777948994, 6789632.30349035 ], [ 157992.72098316113, 6789637.8909134474 ], [ 157988.2395694002, 6789644.3508135546 ], [ 157977.65066585504, 6789658.99995 ], [ 157968.04948488122, 6789672.2901604334 ], [ 157963.14106441895, 6789679.1293983664 ], [ 157951.95046961366, 6789695.38960288 ], [ 157943.36073380499, 6789707.668991575 ], [ 157938.150389413, 6789714.7202124167 ], [ 157927.60893105716, 6789728.8494308861 ], [ 157918.43044358504, 6789740.6602257919 ], [ 157909.46977266262, 6789752.66961521 ], [ 157907.190246991, 6789755.3093602275 ], [ 157896.81915999565, 6789767.3098240485 ], [ 157893.34919140011, 6789771.2303920928 ], [ 157894.55904371943, 6789776.1193873016 ], [ 157919.7502824791, 6789785.8996091187 ], [ 157943.67991053127, 6789793.3190107923 ], [ 157949.94914527773, 6789796.5411509508 ], [ 157973.22963688022, 6789804.2305519031 ], [ 157998.96002551483, 6789813.4105273904 ], [ 158008.09969419579, 6789819.8704274939 ], [ 158018.45568499481, 6789826.8346237754 ], [ 158026.85132684803, 6789833.4150194246 ], [ 158034.56763985916, 6789838.9756657332 ], [ 158048.63513839757, 6789848.7335735597 ], [ 158062.60343335895, 6789855.2537214374 ], [ 158087.60920456157, 6789868.5684792707 ], [ 158096.23128936288, 6789879.297045663 ], [ 158099.87162931857, 6789892.3551926091 ], [ 158099.23974566511, 6789906.3706097296 ], [ 158100.71485972323, 6789907.7339945193 ], [ 158104.91375894961, 6789910.5701026479 ], [ 158109.79198701878, 6789912.2704286873 ], [ 158110.69991540804, 6789912.8394354302 ], [ 158105.48094461835, 6789922.822714556 ], [ 158097.76463160722, 6789940.6359727746 ], [ 158092.09277492226, 6789953.7989954753 ], [ 158085.62513302162, 6789967.8679661704 ], [ 158078.3638625053, 6789985.5674230391 ], [ 158076.32156277855, 6789990.5590626001 ], [ 158071.4411781102, 6790003.8358866517 ], [ 158065.65502165153, 6790018.5854340401 ], [ 158064.6349500881, 6790020.9685681723 ], [ 158062.02546469332, 6790027.7743351227 ], [ 158061.91116491973, 6790034.8099361714 ], [ 158068.94599248876, 6790040.5959537793 ], [ 158069.6253213312, 6790050.240060254 ], [ 158066.90369276225, 6790056.1398792109 ], [ 158058.84663703025, 6790073.5001634313 ], [ 158058.5080509088, 6790074.1807401264 ], [ 158050.33885200287, 6790090.8604476517 ], [ 158045.79921005538, 6790098.801996693 ], [ 158041.71461060236, 6790104.588014299 ], [ 158038.42363976536, 6790109.6934552118 ], [ 158036.83638253319, 6790113.0985700851 ], [ 158031.61741174315, 6790115.0264988225 ], [ 158027.98569818516, 6790116.6152549097 ], [ 158016.8662711631, 6790132.5005843891 ], [ 158011.87374332058, 6790139.9891594332 ], [ 158006.42832958314, 6790147.7031057766 ], [ 158000.30143040384, 6790157.8024176518 ], [ 157992.58511739259, 6790173.6855157325 ], [ 157989.74918905017, 6790179.246162042 ], [ 157983.84873281827, 6790188.7764671706 ], [ 157978.7440618017, 6790196.3788435627 ], [ 157972.27641990129, 6790203.7536172569 ], [ 157969.55263473268, 6790206.364354088 ], [ 157966.60240661667, 6790206.4759240374 ], [ 157950.94549424655, 6790192.7483573901 ], [ 157942.5498523931, 6790186.0541603891 ], [ 157929.27382587106, 6790174.1407211293 ], [ 157932.56479670817, 6790145.6613756921 ], [ 157934.72139620816, 6790126.2593613863 ], [ 157935.51502482407, 6790117.6372356508 ], [ 157944.47785234614, 6790104.4742129501 ], [ 157959.56973564706, 6790082.3498918647 ], [ 157952.64705125219, 6790079.1723796884 ], [ 157943.91066667764, 6790075.5418935157 ], [ 157939.37318132969, 6790071.3446319969 ], [ 157914.52484189067, 6790097.6684460016 ], [ 157891.60450240457, 6790121.7206958206 ], [ 157872.20373330254, 6790142.2584922165 ], [ 157858.36052111222, 6790156.7804369088 ], [ 157832.49211010942, 6790184.0124303056 ], [ 157825.34513936646, 6790191.7263766471 ], [ 157823.07424009335, 6790194.2233121311 ], [ 157808.66599883372, 6790209.5396348657 ], [ 157797.20798569021, 6790222.8119961172 ] ] ], [ [ [ 157775.76060366258, 6790219.1480389591 ], [ 157769.97444720427, 6790218.163992 ], [ 157758.96931995568, 6790215.8946592184 ], [ 157769.98954340082, 6790218.1907687876 ], [ 157775.76060366258, 6790219.1480389591 ] ] ] ] } }
]
}

The second has a little triangle on its side, which size is 0.7 square units. By default prepair should remove it, because it is less than 1.0, but it doesn't. 
prepair --shpOut --setdiff --minarea 4 --ogr in7.shp
does remove it, but when I test the result with Qgis > Outils de géométrie > Vérifier la géométrie,
QGIS 2.2 still finds an auto-intersection where the correction was done.
Here is the geojson source of this second polygon : 

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },

"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 153733.02074695495, 6783092.9053331614 ], [ 153743.11794581404, 6783110.1518160328 ], [ 153757.98122956813, 6783135.7928219438 ], [ 153786.80202528602, 6783131.709361773 ], [ 153800.53093770286, 6783129.6676316876 ], [ 153803.93405171391, 6783129.1008563396 ], [ 153818.797335468, 6783127.0568948565 ], [ 153828.8298363419, 6783125.5016097547 ], [ 153826.05860598444, 6783133.5234891586 ], [ 153823.3369774156, 6783142.8284229897 ], [ 153819.02593501518, 6783157.8055730788 ], [ 153879.70401854708, 6783148.8665886838 ], [ 153885.15158888418, 6783125.1758255018 ], [ 153890.95931133744, 6783125.8095428161 ], [ 153880.06632726302, 6783125.0129333735 ], [ 153882.67581265816, 6783107.8824832495 ], [ 153882.33506993693, 6783101.6412602467 ], [ 153882.10862698953, 6783099.3719274634 ], [ 153882.33722653636, 6783095.2862358959 ], [ 153883.81018399505, 6783080.4251185553 ], [ 153884.94455533195, 6783066.2423465094 ], [ 153881.54144132091, 6783065.675571165 ], [ 153875.75528486248, 6783064.5397890741 ], [ 153873.59868536249, 6783073.0481134616 ], [ 153867.35748640948, 6783072.8227421604 ], [ 153857.14814437646, 6783072.2559668142 ], [ 153839.3907040935, 6783069.7768825265 ], [ 153842.1705608489, 6783040.3715065047 ], [ 153816.86933551496, 6783030.27442603 ], [ 153808.35939388804, 6783025.6219591144 ], [ 153805.29702259798, 6783023.8078317279 ], [ 153804.95412327745, 6783023.8078317288 ], [ 153782.0359403909, 6783026.7577412054 ], [ 153767.17265663715, 6783028.5718685938 ], [ 153751.06070177257, 6783058.9791427655 ], [ 153733.02074695495, 6783092.9053331614 ] ] ] } }
]
}

Hope it will help...
Yours,
AF

**Comment by hugoledoux** [comment]
there's something wrong with your installation of prepair I assume (see issue #11). Here these 2 polygons are properly fixed and QGIS says that the result is valid.

First re-install prepair and ensure that `prepair --wkt 'POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))'`returns a MULTIPOLYGON

**Comment by AlainFELER** [comment]
I did reinstall.

 

prepair --wkt 'POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))'

 

doesn't work but

 

prepair --wkt "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))"

 

does and answers

 

MULTIPOLYGON (((40 40,20 40,10 20,30 10,40 40)))

 

I will try again whith my two #12 polygons.

 

AF

**Comment by AlainFELER** [comment]
I reinstalled prepair_win64 and tried again.

I start with this simplified polygon with one auto-intersection (at 153885.1/6783125.4, 5 m wide 5 cm height) : in geojson :

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 153819.02593501518, 6783157.8055730788 ], [ 153879.70401854708, 6783148.8665886838 ], [ 153885.15158888418, 6783125.1758255018 ], [ 153890.95931133744, 6783125.8095428161 ], [ 153880.06632726302, 6783125.0129333735 ], [ 153883.81018399505, 6783080.4251185553 ], [ 153819.02593501518, 6783157.8055730788 ] ] ] } }
]
}

I repair it with this command :

prepair --shpOut --setdiff --minarea 4 --ogr essais\pbs\in.geojson

 

I verify the geometry of out.shp with QGIS 2.2

It says :

Les segments 0 et 2 de la ligne 0 s'entrecroisent à 153885.104326, 6783125.38136

La géométrie a 1 erreurs

 

I verifiy the geometry of out.shp with OpenJUMP 1.8.0

It finds also an error but different :

Contient un segment avec une longueur inférieure à la longueur minimale,

and it shows in WKT the geometry :

POLYGON ((
        153879.70401854708 6783148.866588684, 
        153885.10432617267 6783125.381364785, 
        153885.10432617273 6783125.381364785, 
        153880.06632726302 6783125.012933373, 
        153883.81018399505 6783080.425118555, 
        153819.02593501518 6783157.805573079, 
        153879.70401854708 6783148.866588684
    ))

 

and in fact the segment between points 2 and 3, created by prepair, is  very short : 6 1/100000000 mm !

The two x differs only by the 17th digit.

In python 2.7.5 inside QGIS 2.2, based on MSVC v. 1500 64 bits, if you divide in float, you have no more than 16 or 17 digits :

> > > 10/3
> > > 3
> > > 10.0/3.0
> > > 3.3333333333333335
> > > 1000.0/3.0
> > > 333.3333333333333
> > > 1000000.0/3.0
> > > 333333.3333333333

 

so maybe the Verify geometry module of QGIS 2.2 is confused by such a short segment...

 

I didn't try yet, but this could also affect the result of geometrical operations like intersects, difference, etc.

 

So maybe it would be wise to avoid creating so short segments with prepair...

 

Yours,

Alain FELER

 

PS1 : it is the command line help of prepair which induced me to my first little mistakes :

C:\prepair_win64>prepair
=== prepair Help ===
Usage:   prepair --wkt 'POLYGON(0 0, 1 0, 1 1, 0 0)'           <--- ' for " and ( ) for (( ))

 

PS2 : is "the Reading only the first feature in the shapefile." a licence issue ?
