### ISSUE TITLE
prepair vs QGIS 2.2 geometry verification

### ISSUE THREAD

**Issue by AlainFELER** [tudelft3d/prepair-qgis#13]
I reinstalled prepair_win64 and tried again.

I try prepair with this simpe polygon with one auto-intersection (at 153885.1/6783125.4, 5 m wide 5 cm height) in geojson :

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },

"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 153819.02593501518, 6783157.8055730788 ], [ 153879.70401854708, 6783148.8665886838 ], [ 153885.15158888418, 6783125.1758255018 ], [ 153890.95931133744, 6783125.8095428161 ], [ 153880.06632726302, 6783125.0129333735 ], [ 153883.81018399505, 6783080.4251185553 ], [ 153819.02593501518, 6783157.8055730788 ] ] ] } }
]
}

I repair it with this command :

prepair --shpOut --setdiff --minarea 4 --ogr essais\pbs\in.geojson

I verify the geometry of out.shp with QGIS 2.2
It says :

"Les segments 0 et 2 de la ligne 0 s'entrecroisent à 153885.104326, 6783125.38136
La géométrie a 1 erreurs"

I verifiy the same geometry of out.shp with OpenJUMP 1.8.0 PLUS (last version)
It finds also an error but different :

"Contient un segment avec une longueur inférieure à la longueur minimale,"

and it shows in WKT the geometry :

POLYGON ((
        153879.70401854708 6783148.866588684,
        153885.10432617267 6783125.381364785,
        153885.10432617273 6783125.381364785,
        153880.06632726302 6783125.012933373,
        153883.81018399505 6783080.425118555,
        153819.02593501518 6783157.805573079,
        153879.70401854708 6783148.866588684
    ))

and in fact the segment between points 2 and 3, created by prepair, is  very short : 6 1/100000000 mm ! The two x differ only by the 17th digit.

In python 2.7.5 inside QGIS 2.2, based on MSVC v. 1500 64 bits, if you divide in float, you have no more than 16 or 17 digits :

> > > 10.0/3.0              3.3333333333333335
> > > 1000.0/3.0          333.3333333333333
> > > 1000000.0/3.0    333333.3333333333
> > > so maybe the Verify geometry module of QGIS 2.2 is confused by such a short segment...

I didn't try yet, but this could also affect the result of geometrical operations like intersects, difference, etc.

??? So maybe it would be wise to avoid creating so short segments with prepair ???

Yours,
Alain FELER

PS1 : it is the command line help of prepair which induced me to my first little mistakes :
C:\prepair_win64>prepair
=== prepair Help ===
Usage:   prepair --wkt 'POLYGON(0 0, 1 0, 1 1, 0 0)'           <--- ' for " and ( ) for (( ))

PS2 : is "the Reading only the first feature in the shapefile." a licence issue ?

**Comment by hugoledoux** [comment]
I am not sure what is happening with the binary under Windows, here I don't get that very small segment. Are you sure you got that POLYGON with prepair? You should have got a MULTIPOLYGON

Validation is (sadly) not an exact science, different software implement different functions. OpenJUMP has a min_segment, which is not "standard" and not in the OGC/ISO rules.

These small segments can indeed affect operations on geometries. prepair has an option to avoid them: 
`--isr GRIDSIZE Snap round the input before repairing`

Yes, there was a mistake in previous versions, one ( was missing. I had not noticed that the Windows binary still has this error, will fix it.
