### ISSUE TITLE
Error when installing on Linux

### ISSUE THREAD

**Issue by gioman** [tudelft3d/prepair-qgis#4]
Python said: "Invalid syntax". cheers!

**Comment by hugoledoux** [comment]
It's not Linux, it's for everything it seems. Submitted a new version earlier today, waiting for it to be approved.

**Comment by hugoledoux** [comment]
New version works, although I had the same error at first. If you install it anyway, then the error doesn't show up again and everything works fine.

**Comment by bmmeijers** [comment]
I think this is because of the name of the folder, which contains dashes ("-")

**Comment by hugoledoux** [comment]
It was, and it's now fixed. However, since the error was in the name, I couldn't submit a new version (system wouldn't accept it).

So I deleted the "old" one, and resubmitted a new plugin. It now works.
