### ISSUE TITLE
Unexpected behavior when changing [executable|save] path setting

### ISSUE THREAD

**Issue by bmmeijers** [tudelft3d/prepair-qgis#5]
If I already have my path to the exe have set up correctly, accidentally click "browse", then click "cancel", the path setting is wiped.

For me, the expected behavior would be that in case I click cancel the previous setting is kept (and not forgotten).

The same holds for the path for saving the repaired polygons shape file.

**Comment by hugoledoux** [comment]
fixed in latest version
