### ISSUE TITLE
Error in running the plugin

### ISSUE THREAD

**Issue by pcav** [tudelft3d/prepair-qgis#7]
It fails on Debian sid:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/prepair/prepair.py", line 180, in run
    wkt2 = (str(self.process.readAllStandardOutput()).splitlines())[0]
IndexError: list index out of range

**Comment by hugoledoux** [comment]
That is because prepair returned nothing. The error is with your installation of prepair, not the plugin I believe.

**Comment by hugoledoux** [comment]
Can you run prepair from the shell? eg what is returned with:
$ ./prepair --wkt 'POLYGON((0 0, 0 10, 10 0, 10 10, 0 0))'

**Comment by pcav** [comment]
Yes, tested. From the shell it works as in the example.

**Comment by pcav** [comment]
I think the error thrown should be more meaningful.

**Comment by hugoledoux** [comment]
that I agree, will fix it. Cheers.

**Comment by hugoledoux** [comment]
fixed in latest version
